#!/bin/bash
set -euo pipefail

echo "Compiling bin/fusc..." >&2
./compile
echo "Compiled OK!" >&2

if test "$#" -eq 0
then
    # Default: names of all .fus files in fus/
    set -- empty min test type
fi


rm -rf _test
mkdir _test

for name in "$@"
do
    echo "========= TESTING: $name ==========" >&2
    bin/fusc --hfile --cfile --main fus/"$name".fus >_test/"$name".c
    gcc --std=c99 -o _test/"$name" _test/"$name".c
done
