#!/bin/bash
set -euo pipefail

echo "Compiling bin/fusc..." >&2
./compile
echo "Compiled OK!" >&2

FUSC_ARGS=
while test "$#" -ge 1
do
    case "$1" in
        --) shift; break;;
        -*) FUSC_ARGS="$FUSC_ARGS $1"; shift;;
        *) break;;
    esac
done

if test "$#" -eq 0
then
    # Default: names of all .fus files in fus/
    set -- empty min any test graphs file geom functions
fi


rm -rf _test
mkdir _test

for name in "$@"
do
    echo "========= TESTING: $name ==========" >&2
    if test -f fus/"$name".h; then
        echo "#include \"../fus/$name.h\"" >>_test/"$name".c
    fi
    bin/fusc $FUSC_ARGS -a fus/"$name".fus >>_test/"$name".c
    gcc --std=c99 -o _test/"$name" _test/"$name".c
done
